spring:
  security:
    user:
      name: ${SPRINGSECUSER:admin}
      password: ${SPRINGSECPASS:admin}
  r2dbc:
    url: ${DBURL:r2dbc:postgresql://localhost:5432/crowellchatdb}
    username: ${DBUSERNAME:postgres}
    password: ${DBPASSWORD:CrowellChatPassword}
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: drop-and-create
              create-target: create.sql
              create-source: metadata
  data:
    rest:
      basePath: ${API_ROUTE:/api/v1}
springdoc:
  paths-to-match: ${API_ROUTE:/api/v1/**}
  api-docs:
      enabled: true
  swagger-ui:
    enabled: true
    csrf:
      enabled: false
    path: /swagger-ui.html
  show-actuator: true